### ISSUE TITLE
Version 5.2.1 Temp fixes & needs work

### ISSUE THREAD

**Issue by m-ristau** [m-ristau/adminer-filamentish#1]
I noticed **5.2.1** brings up some small things to adjust.
Better late then never - I fixed the issues just for now.

**Will be back with the long termed one for:**
> 1. Work #menu, .logout & .footer
> 2. Handle "new" img#logo
> 2. Check responsive mode

```css
input[type="submit"],
input[type="button"] {
    columns: var(--color-white);
}
button.icon.icon-move {
    border-radius: 0;
    background-color: var(--color-background-shade);
    opacity: 1;
    color: var(--color-text-highlight);
}
#menu h1 #logo {
    display: none;
}
p.logout {
    background: none;
    box-shadow: none;
}
div.footer  {
    box-shadow: none;
    bottom: auto;
}
@media all and (max-width:800px) {
  #menu {
    box-shadow: none;
    border-color: var(--color-border);
  }
}
```
